### PR TITLE
Grid view placeholder

### PR DESCRIPTION
**Pull request by romancm**
- Updated grid placeholder to closer resemble layout
- Applied theme colors to placeholder

Screen Shot 2019-12-16 at 3 48 08 PM

### CODE REVIEW

**Comment by paddykontschak** [comment]
Maybe the text-only views should only show text preview, too?

**Comment by romancm** [comment]
>Maybe the text-only views should only show text preview, too?

What text would you use if the game data isn't loaded yet?

**Comment by paddykontschak** [comment]
I meant the 2 lines indicating text. Currently if a list is set to “text only” the preview still shows a thumbnail next to the text.

This view basically needs the reverse of this PR’s addition.

**Comment by romancm** [comment]
Ahh, that's true, I didn't even notice, I'll update text view as well 👍

**Pull request merged**
